name: Node.js CI with File Increment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  increment_file:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increment value
      run: |
        FILE="counter.txt"
        if [ ! -f "$FILE" ]; then
          echo "0" > $FILE
        fi
        CURRENT=$(cat $FILE)
        INCREMENTED=$((CURRENT + 1))
        echo $INCREMENTED > $FILE
        echo "Incremented value: $INCREMENTED"

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add counter.txt
        git commit -m "Incremented counter value to $INCREMENTED"
        git push
